version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ghly-redis
    ports:
      - "6374:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  ghly:
    image: ghcr.io/quonaro/ghly:master
    container_name: ghly
    ports:
      - "${SERVER_PORT-8000}:${SERVER_PORT-8000}"
    env_file:
      - .env
    # The command is already defined in the Dockerfile, but we can override it if needed.
    # command: python app/main.py
    depends_on:
      - redis
  

volumes:
  redis-data:
    driver: local
